### ISSUE TITLE
Add keyboard shortcut for "stop playing music"

### ISSUE THREAD

**Issue by tmickel** [supernoteworthy/noteworthy#12]

**Comment by thechutrain** [comment]
@tmickel looks like I could just call the `Audio.stopAll()` function within the "keypress" event listener. Is there any particular key that should be associated with stoping the audio?

https://github.com/tmickel/noteworthy/blob/master/src/PlayControls/PlayControls.tsx#L8

**Comment by tmickel** [comment]
Yes, that should do it!

So the current set of shortcuts is space to play the current sheet and enter to play everything. I think "escape" could work well for stop but I'm not sure if the browser reports that to the keyboard handler. Another option might be delete/backspace (but might regret that later if you can select notes and press delete to delete them...). Maybe, if you press enter/space while it's playing already, it should stop? It doesn't make that much sense for it to start a new player in parallel (which is what it currently does)?

**Comment by tmickel** [comment]
actually https://stackoverflow.com/questions/3369593/how-to-detect-escape-key-press-with-pure-js-or-jquery seems to imply that escape is detectable so maybe escape!

**Comment by tmickel** [comment]
(but not with keypress, what it's currently using, just with keyup or keydown)
